apiVersion: v1
data:
  create.sql: "CREATE DATABASE db_paymybuddy;\nUSE db_paymybuddy;\n\nCREATE TABLE
    user (\n    user_id INT NOT NULL PRIMARY KEY AUTO_INCREMENT,\n    email VARCHAR(100)
    NOT NULL UNIQUE,\n    password VARCHAR(100) NOT NULL,\n    firstname VARCHAR(50)
    NOT NULL,\n    lastname VARCHAR(50) NOT NULL,\n    balance DECIMAL(10, 2) NOT
    NULL DEFAULT 0.0\n);\n\nCREATE TABLE bank_account(\n    account_id INT NOT NULL
    AUTO_INCREMENT,\n    fk_user_id INT NOT NULL,\n    bank_name VARCHAR(100) DEFAULT
    NULL,\n    iban VARCHAR(34) DEFAULT NULL,\n    balance DECIMAL(20,2) NOT NULL
    DEFAULT 0.0,\n    PRIMARY KEY (account_id, fk_user_id),\n    FOREIGN KEY (fk_user_id)\n
    \       REFERENCES user (user_id)\n        ON DELETE NO ACTION ON UPDATE NO ACTION\n);\n\nCREATE
    TABLE connection (\n    connection_id INT NOT NULL AUTO_INCREMENT,\n    fk_initializer_id
    INT NOT NULL,\n    fk_receiver_id INT NOT NULL,\n    starting_date DATETIME NOT
    NULL,\n    FOREIGN KEY (fk_initializer_id)\n        REFERENCES user (user_id)\n
    \       ON DELETE NO ACTION ON UPDATE NO ACTION,\n    FOREIGN KEY (fk_receiver_id)\n
    \       REFERENCES user (user_id)\n        ON DELETE NO ACTION ON UPDATE NO ACTION,\n
    \   PRIMARY KEY (connection_id, fk_initializer_id, fk_receiver_id)\n);\n\nCREATE
    TABLE transaction (\n    transaction_id INT NOT NULL AUTO_INCREMENT,\n    fk_issuer_id
    INT NOT NULL,\n    fk_payee_id INT NOT NULL,\n    date DATETIME NOT NULL,\n    amount
    DECIMAL(10, 2) NOT NULL,\n    description VARCHAR(140),\n    FOREIGN KEY (fk_issuer_id)\n
    \       REFERENCES user (user_id)\n        ON DELETE NO ACTION ON UPDATE NO ACTION,\n
    \   FOREIGN KEY (fk_payee_id)\n        REFERENCES user (user_id)\n        ON DELETE
    NO ACTION ON UPDATE NO ACTION,\n    PRIMARY KEY (transaction_id, fk_issuer_id,
    fk_payee_id)\n);\n\nINSERT INTO `user` (`email`, `password`, `firstname`, `lastname`,
    `balance`) VALUES\n\t('security@mail.com', '$2a$10$vpDkNfBtWg.ebbkL8VwaG.BrmlIlqRCd0RqoyOIb6hgRZRMfJ51xa',
    'Security', 'User', 0.00),\n\t('hayley@mymail.com', '$2a$10$1NDocQWD9pl52dv/cY7mmOuCYbIVTzCd6ahb5EUDQxwkDMkg1Q54y',
    'Hayley', 'James', 10.00),\n\t('clara@mail.com', '$2a$10$41nUyaddehEi9Slu/4kFWeedO3YrLnGCu5nZqYySX3CH7uyHMrclu',
    'Clara', 'Tarazi', 133.56),\n\t('smith@mail.com', '$2a$10$3TU.lRztZJgEueboxsP2b.AV6TeBsKK.qyyCYGYJXKeozeahFVTuu',
    'Smith', 'Sam', 8.00),\n\t('lambda@mail.com', '$2a$10$prOZuMO22K.itqO3CKrEGuVf2KUxdWOB9fGQh8DvWHPHWIiiR6iZy',
    'Lambda', 'User', 96.91);\n\nINSERT INTO `bank_account` (`fk_user_id`, `bank_name`,
    `iban`, `balance`) VALUES\n    (5, 'Banque de France', 'FR7630001007941234567890185',
    1590.00),\n    (2, 'BNP Paribas', 'FR7630004000031234567890143', 352.68),\n    (3,
    'Crédit Agricole', 'FR7630006000011234567890189', 20.00),\n    (4, 'Banque Populaire',
    'FR7610107001011234567890129', 0.00);\n\t\nINSERT INTO `connection` (`fk_initializer_id`,
    `fk_receiver_id`, `starting_date`) VALUES\n\t(1, 2, '2022-10-24 17:37:33'),\n\t(1,
    3, '2022-10-24 17:37:41'),\n\t(3, 4, '2022-10-24 17:38:01'),\n\t(3, 5, '2022-10-24
    17:38:08'),\n\t(5, 2, '2022-10-24 17:38:29'),\n\t(5, 4, '2022-10-24 17:38:39');\n\nINSERT
    INTO `transaction` (`fk_issuer_id`, `fk_payee_id`, `date`, `amount`, `description`)
    VALUES\n\t(5, 4, '2022-10-24 17:39:55', 8.00, 'Movie tickets'),\n\t(3, 5, '2022-10-24
    17:41:03', 25.00, 'Trip money'),\n\t(5, 2, '2022-10-24 17:41:40', 10.00, 'Restaurant
    bill share');\n"
kind: ConfigMap
metadata:
  creationTimestamp: null
  name: initdb-config
