apiVersion: apps/v1
kind: Deployment
metadata:
  name: paymybuddy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: paymybuddy
  template:
    metadata:
      labels:
        app: paymybuddy
    spec:
      containers:
      - name: backend
        image: ssagnane/paymybuddy:latest
        ports:
        - containerPort: 8080
        env:
        - name: SPRING_DATASOURCE_USERNAME
          valueFrom:
            secretKeyRef:
              name: mysql-credentials
              key: username
        - name: SPRING_DATASOURCE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-credentials
              key: password
        - name: SPRING_DATASOURCE_URL
          valueFrom:
            configMapKeyRef:
              name: paymybuddy-config
              key: SPRING_DATASOURCE_URL
